# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neubird < Formula
  desc "AI-powered SRE platform"
  homepage "https://neubird.ai"
  version "1.0.59"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neubirdai/neubird-desktop/releases/download/v1.0.59/neubird_1.0.59_darwin_amd64.tar.gz"
      sha256 "e3303f35b0d6f7ff1778856b782b35bb5900e3c0116656ce98c6b2b4ec94a499"

      define_method(:install) do
        bin.install "neubird"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neubirdai/neubird-desktop/releases/download/v1.0.59/neubird_1.0.59_darwin_arm64.tar.gz"
      sha256 "48e463d667b0a1d472e073844f20378466529249b3a0a4b66e388c19d996f595"

      define_method(:install) do
        bin.install "neubird"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/neubirdai/neubird-desktop/releases/download/v1.0.59/neubird_1.0.59_linux_amd64.tar.gz"
      sha256 "848de6dfd3bd8178c171ee0de32195812d42b7e2093881101bc40eb5fd49f052"
      define_method(:install) do
        bin.install "neubird"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neubirdai/neubird-desktop/releases/download/v1.0.59/neubird_1.0.59_linux_arm64.tar.gz"
      sha256 "eb5948b82eafee0134d30d5fe0e83d5c72ea90cffcd0ee69833bb03bc3ec37e6"
      define_method(:install) do
        bin.install "neubird"
      end
    end
  end
end
