# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neubird < Formula
  desc "AI-powered SRE platform"
  homepage "https://neubird.ai"
  version "1.0.37"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neubirdai/neubird-desktop/releases/download/v1.0.37/neubird_1.0.37_darwin_amd64.tar.gz"
      sha256 "737838f11fe9c828e8cb538cf1f634d8b259ab371ac150cb0ee7ade2a5ce1ca6"

      define_method(:install) do
        bin.install "neubird"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neubirdai/neubird-desktop/releases/download/v1.0.37/neubird_1.0.37_darwin_arm64.tar.gz"
      sha256 "d9b45c740ecad20353ac2bac13626c56270da9a57c36f924788cb1cadc80c143"

      define_method(:install) do
        bin.install "neubird"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/neubirdai/neubird-desktop/releases/download/v1.0.37/neubird_1.0.37_linux_amd64.tar.gz"
      sha256 "09e01909ecffbf8c0a5d9b9c165f8f58ca4e1b3eb82cf74d0320d50a8852df34"
      define_method(:install) do
        bin.install "neubird"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neubirdai/neubird-desktop/releases/download/v1.0.37/neubird_1.0.37_linux_arm64.tar.gz"
      sha256 "1b7dd6332d0fa17a016d71e9d9d6974478a027c5b406c4ed70d6ff137b0876c8"
      define_method(:install) do
        bin.install "neubird"
      end
    end
  end
end
