# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NeubirdTerminal < Formula
  desc "AI-powered SRE platform"
  homepage "https://neubird.ai"
  version "1.0.90"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neubirdai/neubird-terminal/releases/download/v1.0.90/neubird_1.0.90_darwin_amd64.tar.gz"
      sha256 "1b9e7bbde848a6db1c5cd5c8ef17ed8d75641005334b97453947328cf6f515cf"

      define_method(:install) do
        bin.install "neubird"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neubirdai/neubird-terminal/releases/download/v1.0.90/neubird_1.0.90_darwin_arm64.tar.gz"
      sha256 "c7fcbea01bd57d697e43396120fb914666173f748439614ed02c7fc42bfd938c"

      define_method(:install) do
        bin.install "neubird"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/neubirdai/neubird-terminal/releases/download/v1.0.90/neubird_1.0.90_linux_amd64.tar.gz"
      sha256 "8e6098df8147ed9eff77f176e8643aee2a828eb7c3b2dd665f4b4d3fea7aa11f"
      define_method(:install) do
        bin.install "neubird"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neubirdai/neubird-terminal/releases/download/v1.0.90/neubird_1.0.90_linux_arm64.tar.gz"
      sha256 "a142e0a59a7dcf1ffc64e52269ee1ac680a21955bdb7c070a87bef6fd3af33b1"
      define_method(:install) do
        bin.install "neubird"
      end
    end
  end
end
