# typed: false
# frozen_string_literal: true

# Auto-generated by neubirdai/falcon-app's desktop-shell-release
# workflow (main branch). Manual edits will be overwritten.
cask "neubird-desktop" do
  version "0.2.108"
  sha256 "f6844d93816f168e96c5416264b4ed0b6e7ad369894a9e5413d4be2a88c08fc8"

  url "https://github.com/neubirdai/neubird-desktop/releases/download/shell-v#{version}/NeubirdDesktopShell-0.2.108-darwin-universal.dmg"
  name "NeuBird Desktop"
  desc "AI-native workspace for SRE operations (Wails shell)"
  homepage "https://neubird.ai/"

  depends_on macos: :big_sur

  # Same target name (and case) the fork's cask used, so brew
  # upgrade cleanly swaps the Electron app for the shell.
  # (NO backticks anywhere in this heredoc: it is UNQUOTED so the
  # shell expands 0.2.108 etc — backticks would command-substitute,
  # which corrupted the published cask once already.)
  app "neubird-desktop.app", target: "Neubird Desktop.app"

  # Strip the quarantine attribute Homebrew sets on every download.
  # Needed until notarized builds ship (the workflow notarizes only
  # once the Developer ID secrets are configured) — without it, an
  # un-notarized first launch shows "damaged and can't be opened".
  # Remove this block once releases are reliably notarized.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-r", "-d", "com.apple.quarantine", "#{appdir}/Neubird Desktop.app"],
                   sudo: false
  end

  zap trash: [
    "~/.config/neubird/falcon-desktop.json",
    "~/Library/Caches/ai.neubird.falcon-shell",
    "~/Library/WebKit/ai.neubird.falcon-shell",
    "~/Library/Preferences/ai.neubird.falcon-shell.plist",
    "~/Library/Saved Application State/ai.neubird.falcon-shell.savedState",
  ]
end
