# typed: false
# frozen_string_literal: true

# This file is auto-generated by neubirdai/falcon-app's release
# workflow. Manual edits will be overwritten on the next release.
# See: https://github.com/neubirdai/falcon-app/blob/neubird-main/.github/workflows/release.yml
cask "neubird-desktop" do
  version "0.1.72"
  sha256 "80e2d2e0ae6b22f0e540d69d2ddd9d251e9f0dbd043cf4f5c2066bf707f265f6"

  url "https://github.com/neubirdai/neubird-desktop/releases/download/v#{version}/NeubirdDesktop-darwin-arm64.dmg"
  name "Neubird Desktop"
  desc "AI-native workspace for SRE operations"
  homepage "https://neubird.ai/"

  # We only ship arm64 today. Intel users get a clear error from
  # brew instead of an exec-format failure at first launch.
  depends_on macos: :catalina, arch: :arm64

  app "Neubird Desktop.app"

  # Strip the macOS quarantine attribute that Homebrew Cask sets
  # by default on every download. Without this, first launch
  # shows "Neubird Desktop is damaged and can't be opened" with
  # no escape from the UI -- because we don't yet ship Apple-
  # notarized builds. Remove this block once we have a Developer
  # ID and notarization wired up in the build.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-r", "-d", "com.apple.quarantine", "#{appdir}/Neubird Desktop.app"],
                   sudo: false
  end

  # Things Falcon and the bundled neubird sidecar drop on disk.
  zap trash: [
    "~/.neubird-falcon",
    "~/Library/Application Support/Neubird Desktop",
    "~/Library/Caches/ai.neubird.falcon",
    "~/Library/Caches/Neubird Desktop",
    "~/Library/Logs/Neubird Desktop",
    "~/Library/Preferences/ai.neubird.falcon.plist",
    "~/Library/Saved Application State/ai.neubird.falcon.savedState",
  ]
end
