# typed: false
# frozen_string_literal: true

# Auto-generated by neubirdai/falcon-app's desktop-shell-release
# workflow (desktop-shell branch). Manual edits will be overwritten.
cask "neubird-desktop-shell" do
  version "0.1.2"
  sha256 "4dfd11ae6bdf6dda8e9f73ac7eadce1be3890f2234f5a03622b4ca25b669de1d"

  url "https://github.com/neubirdai/neubird-desktop/releases/download/shell-v#{version}/NeubirdDesktopShell-0.1.2-darwin-universal.dmg"
  name "NeuBird Desktop (shell)"
  desc "AI-native workspace for SRE operations (Wails shell)"
  homepage "https://neubird.ai/"

  depends_on macos: :big_sur

  app "neubird-wails.app", target: "NeuBird Desktop.app"

  # Strip the quarantine attribute Homebrew sets on every download.
  # Needed until notarized builds ship (the workflow notarizes only
  # once the Developer ID secrets are configured) — without it, an
  # un-notarized first launch shows "damaged and can't be opened".
  # Remove this block once releases are reliably notarized.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-r", "-d", "com.apple.quarantine", "#{appdir}/NeuBird Desktop.app"],
                   sudo: false
  end

  zap trash: [
    "~/.config/neubird/falcon-desktop.json",
    "~/Library/Caches/ai.neubird.falcon-shell",
    "~/Library/WebKit/ai.neubird.falcon-shell",
    "~/Library/Preferences/ai.neubird.falcon-shell.plist",
    "~/Library/Saved Application State/ai.neubird.falcon-shell.savedState",
  ]
end
